# Generated by Django 3.2.3 on 2021-06-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfGeneration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
