# Generated by Django 3.2.3 on 2021-06-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfGeneration', '0003_rename_logo_logo_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
